### ISSUE TITLE
Nightly build is failing on macos because it can't build Ruby

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/distribution-scripts#145]
https://app.circleci.com/pipelines/github/crystal-lang/crystal/6938/workflows/19a6d680-05e1-44af-8302-969bbe1efc05/jobs/64236

```
compiling vm.c
In file included from vm.c:344:
./vm_insnhelper.c:5045:43: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
        fprintf(stderr, "%s %s(%d):%p\n", RUBY_FUNCTION_NAME_STRING, bf->name, bf->argc, bf->func_ptr);
...
make: *** [vm.o] Error 1
!!! Compiling ruby 2.7.3 failed!

```

**Comment by straight-shoota** [comment]
Looks similar to this: https://github.com/rvm/rvm/issues/5047#issuecomment-844985557

**Comment by straight-shoota** [comment]
@bcardiff What's the reason that we're building Ruby ourselves with `ruby-install` vs. installing Ruby via homebrew, for example?

**Comment by straight-shoota** [comment]
While investigating this, a different error showed up with openssl. [Ruby does not yet work with OpenSSL 3.0](https://github.com/ruby/openssl/issues/369) but that's installed via homebrew. This issue is tracked in https://github.com/postmodern/ruby-install/issues/409 and fixed in the latest release of `ruby-install` (`0.8.3`). So I suppose we just need to run `brew update ruby-install` until the update is propagated into the CI runner base system.
